# python casia_Lenet.py -i='/home/bea/Desktop/THEANO/datasetGenerator/mfsd_positivas_negativas_128_128.pkl' -o='multispectral_4/mfsd/'
# python casia_Lenet.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_positivas_negativas_128_128.pkl' -o='frav_4/'
# python casia_Lenet.py -i='/home/bea/Desktop/THEANO/datasetGenerator/casia_positivas_negativas_128_128.pkl' -o='multispectral_4/casia/'
# python casia_Lenet.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_rgb_positivas_negativas_128_128_reduced.pkl' -o='reduced_frav_4/'
# python casia_Lenet_ch1.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_nir_positivas_negativas_128_128_reduced.pkl' -o='reduced_frav_nir_4/'
# python casia_Lenet_ch1.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_thermal_positivas_negativas_128_128_reduced.pkl' -o='reduced_frav_thermal_4/'
# python casia_Lenet.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_rgb_positivas_negativas_128_128_reduced.pkl' -o='reduced_frav_4/'
# python casia_Lenet_feat.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_multispectral_positivas_negativas_128_128_reduced__merged.pkl' -o='multispectral_2_3/frav_multi_feat/'
python casia_Lenet_clas.py -i='/home/bea/Desktop/THEANO/datasetGenerator/frav_multispectral_positivas_negativas_128_128_reduced__separated.pkl' -o='/home/bea/Desktop/PublicacionTFM/Experimentos/Experimento_genuine_attacks/la/'
